module.exports = {
    emailRegex: /^\w+@[a-zA-Z.]+$/,
    onlyDigitsRegex: /^[0-9\+ ]+$/,
    dateRegex: /\d{2}\/\d{2}\/\d{4}\s\d{2}\:\d{2}\s[A-Z]{2}/,
    invalidUsername: 'Полето Потребителско име трябва да съдържа между 3 и 15 символа',
    uniqueUsername: 'Вече съществува потребител с това потребителско име',
    invalidPassword: 'Полето Парола трябва да съдържа между 3 и 15 символа',
    invalidFirstName: 'Полето Име трябва да съдържа между 3 и 15 символа',
    invalidLastName: 'Полето Фамилия трябва да съдържа между 3 и 15 символа',
    invalidEmail: 'Невалиден e-mail',
    invalidNumber: 'Полето Телефонен номер може да съдърша само цифри',
    invalidCountry: 'Полето Държава трябва да съдържа между 1 и 30 символа',
    invalidOfferType: 'Невалидна дестинация',
    invalidTown: 'Полето Град трябва да съдържа между 1 и 30 символа',
    invalidDateFormat: 'Невалиден формат на датата',
    invalidPrice: 'Полето Цена може да съдърша само цифри',
    invalidDescription: 'Полето Описание трябва да съдържа между 5 и 150 символа',
    invalidNumberOfPictures: 'Може да качите само до 3 снимки',
    invalidUserImageLength: 'Трябва да изберете 1 снимка',
    invalidMessageLength: 'Полето Коментар трябва да съдържа между 5 и 150 символа',
    invalidRate: 'Стойността на полето Рейтинг трявбва да е между 1 и 5',
};
